#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

#
# NeuroNarrator: move the backend from a teammate's Supabase project onto YOUR
# own free Supabase project.
#
# Run from anywhere:  ./scripts/setup-own-backend.sh
#
# Key safety rules this script follows:
#   - API keys are typed with hidden input (read -s), never echoed, never put
#     on a command line you typed (so never in shell history), and never
#     written to any file inside the repo.
#   - They are handed to the Supabase CLI through a temporary file in your
#     system temp dir (permissions 600 = only you can read it) that is deleted
#     as soon as the command finishes, or when the script exits for any reason.
#   - Every command that changes something remote or local asks first.

# Always work from the repo root, so .env and supabase/ resolve correctly.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
ENV_FILE="$REPO_ROOT/.env"
BACKUP_FILE="$REPO_ROOT/.env.teammate.bak"
FUNCTIONS=(analyze-image text-to-speech speech-to-text)

# Captured values. Deliberately NOT named like the .env keys, so the library's
# "Enter keeps current" default never silently offers the teammate's values.
NEW_PROJECT_REF=""; NEW_SUPABASE_URL=""; NEW_PUBLISHABLE_KEY=""
GROQ_KEY=""; SARVAM_KEY=""; ANTHROPIC_KEY=""
SECRETS_TMP=""

# If anything goes wrong, never leave a key file behind.
cleanup() {
  if [[ -n "$SECRETS_TMP" && -f "$SECRETS_TMP" ]]; then rm -f "$SECRETS_TMP"; fi
}
trap cleanup EXIT INT TERM

# run "cmd ..." shows a command, then runs it. Callers confirm() first.
run() {
  printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"
  "$@"
}

# exclude_locally PATTERN adds PATTERN to .git/info/exclude: a per-clone
# ignore list that is never committed (unlike .gitignore, which is shared).
exclude_locally() {
  local pattern="$1" exclude_file
  exclude_file="$(git rev-parse --git-path info/exclude)"
  mkdir -p "$(dirname "$exclude_file")"
  touch "$exclude_file"
  if ! grep -qxF "$pattern" "$exclude_file"; then
    printf '%s\n' "$pattern" >> "$exclude_file"
    printf '  %s✓ git will now ignore%s %s %s(local only, via .git/info/exclude)%s\n' \
      "$GREEN" "$RESET" "$pattern" "$DIM" "$RESET"
  fi
}

# check_prefix VALUE PREFIX LABEL warns (does not block) on an unexpected
# prefix, which usually means the wrong thing was copied.
check_prefix() {
  if [[ -n "$1" && "$1" != "$2"* ]]; then
    warn "$3 usually starts with '$2'. Double-check you copied the right value."
  fi
}

TOTAL_STAGES=11

banner "NeuroNarrator: run the backend on your own Supabase project"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check your tools and learn the vocabulary"
say "This checks you have what's needed, and explains the words used later."
printf '\n'
note "Supabase       = a hosted backend service (database, auth, serverless code)."
note "Edge function  = a small server-side program Supabase runs for you on demand."
note "                 This app has 3: analyze-image, text-to-speech, speech-to-text."
note "                 They exist so API keys stay on the server, not in the browser."
note "Secret         = a value (like an API key) stored inside Supabase that only"
note "                 your edge functions can read. The browser never sees it."
note "Supabase CLI   = the 'supabase' command-line tool. You don't have it installed;"
note "                 'npx supabase ...' downloads and runs it via npm on demand."
printf '\n'
command -v node >/dev/null 2>&1 || { warn "node not found. Install Node.js first."; exit 1; }
command -v npx  >/dev/null 2>&1 || { warn "npx not found. It ships with npm; reinstall Node.js."; exit 1; }
command -v git  >/dev/null 2>&1 || { warn "git not found."; exit 1; }
command -v curl >/dev/null 2>&1 || { warn "curl not found."; exit 1; }
printf '  %s✓%s node %s, npx, git, curl found\n' "$GREEN" "$RESET" "$(node --version)"
say "Repo: $REPO_ROOT  (branch: $(git branch --show-current 2>/dev/null || echo '?'))"
note "Docker is NOT needed: we deploy with the Supabase API instead of a local build."
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create your free Supabase project"
say "You need your own project so the app stops depending on a teammate's account."
open_url "https://supabase.com/dashboard"
step "Sign up / sign in (GitHub login is quickest)."
step "Click 'New project'. Pick your organization (a free one is created for you)."
step "Name it e.g. 'neuronarrator'. Choose a region near you (e.g. Mumbai / ap-south-1)."
step "Set a database password and SAVE it in a password manager (the app doesn't use"
step "  the database, but Supabase may ask for it later)."
step "Plan: Free. Click 'Create new project' and wait ~1-2 minutes until it's ready."
printf '\n'
note "Project ref = your project's unique ID: 20 lowercase letters, e.g. abcdefghijklmnopqrst."
note "It appears in the dashboard URL (supabase.com/dashboard/project/<ref>) and in"
note "Project Settings → General → 'Project ID'."
while true; do
  ask NEW_PROJECT_REF "Paste your project ref:"
  NEW_PROJECT_REF="$(printf '%s' "$NEW_PROJECT_REF" | tr -d '[:space:]')"
  if [[ "$NEW_PROJECT_REF" =~ ^[a-z]{20}$ ]]; then break; fi
  warn "That doesn't look like a project ref (expected 20 lowercase letters). Try again."
done
if [[ "$NEW_PROJECT_REF" == "yvqujhdozlzogusxrwgi" ]]; then
  warn "That's the TEAMMATE's project ref (from supabase/config.toml). Use your own."
  exit 1
fi
NEW_SUPABASE_URL="https://${NEW_PROJECT_REF}.supabase.co"
printf '  %s✓%s Project URL will be %s\n' "$GREEN" "$RESET" "$NEW_SUPABASE_URL"
note "(Project URL = the web address of your backend. It's always https://<ref>.supabase.co)"
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Copy your publishable (anon) key"
say "The browser app needs this key to be allowed to call your edge functions."
note "Publishable key (older name: anon key) = a PUBLIC key that identifies your project"
note "to Supabase. It's safe in browser code; it is NOT a secret. Never use the"
note "'secret' / 'service_role' key here: that one bypasses all security."
open_url "https://supabase.com/dashboard/project/${NEW_PROJECT_REF}/settings/api-keys"
step "Project Settings → API Keys."
step "Copy the Publishable key (starts with sb_publishable_). If you only see"
step "  'Legacy API keys', copy the 'anon' 'public' key (a long string starting eyJ)."
while true; do
  ask NEW_PUBLISHABLE_KEY "Paste the publishable/anon key:"
  NEW_PUBLISHABLE_KEY="$(printf '%s' "$NEW_PUBLISHABLE_KEY" | tr -d '[:space:]')"
  if [[ "$NEW_PUBLISHABLE_KEY" == sb_secret_* ]]; then
    warn "That's a SECRET key. Copy the publishable one instead."; continue
  fi
  if [[ "$NEW_PUBLISHABLE_KEY" == sb_publishable_* || "$NEW_PUBLISHABLE_KEY" == eyJ* ]]; then break; fi
  warn "Expected a key starting with sb_publishable_ or eyJ. Try again."
done
printf '  %s✓%s got it (kept in memory; written to .env in stage 9)\n' "$GREEN" "$RESET"
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Get a Groq API key (required)"
say "analyze-image sends camera frames to Groq's vision model, so it needs a Groq key."
note "API key = a password that lets a program use a paid/free service on your account."
note "Groq has a free tier; no card needed at the time of writing."
open_url "https://console.groq.com/keys"
step "Sign up / sign in."
step "Click 'Create API Key', name it 'neuronarrator', and copy it (starts gsk_)."
step "Groq shows it only once. If you lose it, just create another."
note "Your typing will be hidden. The key stays in this script's memory only."
while [[ -z "$GROQ_KEY" ]]; do
  ask_secret GROQ_KEY "Paste your Groq API key:"
  GROQ_KEY="$(printf '%s' "$GROQ_KEY" | tr -d '[:space:]')"
  [[ -z "$GROQ_KEY" ]] && warn "The Groq key is required for the vision feature."
done
check_prefix "$GROQ_KEY" "gsk_" "A Groq key"
printf '  %s✓%s Groq key captured (%s characters)\n' "$GREEN" "$RESET" "${#GROQ_KEY}"
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Optional keys: Sarvam (voice) and Anthropic (vision fallback)"
say "These are optional; press Enter to skip either one."
note "Sarvam powers natural Indian-English voice (text-to-speech, speech-to-text)."
note "Without it, the app falls back to your browser's built-in speech. That works fine."
if confirm "Open the Sarvam dashboard to get a key?"; then
  open_url "https://dashboard.sarvam.ai"
  step "Sign in → API keys → create/copy a key."
fi
ask_secret SARVAM_KEY "Paste Sarvam API key (Enter to skip):"
SARVAM_KEY="$(printf '%s' "$SARVAM_KEY" | tr -d '[:space:]')"
printf '\n'
note "Anthropic (Claude) is a backup vision model used only if every Groq model fails."
note "Anthropic has no free tier: it needs billing set up. Skipping is normal."
if confirm "Open the Anthropic console to get a key?"; then
  open_url "https://console.anthropic.com/settings/keys"
  step "Create Key → copy it (starts sk-ant-)."
fi
ask_secret ANTHROPIC_KEY "Paste Anthropic API key (Enter to skip):"
ANTHROPIC_KEY="$(printf '%s' "$ANTHROPIC_KEY" | tr -d '[:space:]')"
check_prefix "$ANTHROPIC_KEY" "sk-ant-" "An Anthropic key"
note "(LOVABLE_API_KEY is skipped on purpose: it only works inside Lovable Cloud.)"
[[ -n "$SARVAM_KEY" ]]    && printf '  %s✓%s Sarvam key captured\n' "$GREEN" "$RESET"
[[ -n "$ANTHROPIC_KEY" ]] && printf '  %s✓%s Anthropic key captured\n' "$GREEN" "$RESET"
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Log the Supabase CLI in and link this repo to your project"
say "Login lets the CLI act on your account; linking tells it which project to target."
note "Login opens a browser and stores an access token in your home folder (not the repo)."
note "Link remembers your project ref in supabase/.temp/, which we keep out of git."
printf '\n'
note "About supabase/config.toml: its project_id (yvqujhdozlzogusxrwgi) is the teammate's."
note "That field only names the LOCAL Docker dev stack; it does NOT choose where deploys"
note "go. The linked ref (and the --project-ref we pass explicitly on every command)"
note "decides that. So we leave config.toml unchanged: no diff, no merge conflicts."
printf '\n'
exclude_locally "supabase/.temp/"
if confirm "Run 'npx supabase login' now?"; then
  run npx --yes supabase login || { warn "Login failed. Re-run the wizard to try again."; exit 1; }
else
  SKIPPED+=("npx supabase login")
fi
note "Link may ask for your database password. Type it, or press Enter to skip;"
note "deploying functions and setting secrets don't need it."
if confirm "Run 'npx supabase link --project-ref ${NEW_PROJECT_REF}' now?"; then
  run npx --yes supabase link --project-ref "$NEW_PROJECT_REF" \
    || { warn "Link failed. Check the ref and that login succeeded."; exit 1; }
else
  SKIPPED+=("npx supabase link --project-ref ${NEW_PROJECT_REF}")
fi
pause "Press Enter to continue"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Store your API keys as Supabase secrets"
say "Edge functions read keys from secrets, so the keys never ship to the browser."
note "How the keys travel: written to a temp file OUTSIDE the repo (in \$TMPDIR),"
note "readable only by you (chmod 600), passed to the CLI with --env-file, then"
note "deleted immediately. They are never on a command line, so never in history."
names=("GROQ_API_KEY")
[[ -n "$SARVAM_KEY" ]]    && names+=("SARVAM_API_KEY")
[[ -n "$ANTHROPIC_KEY" ]] && names+=("ANTHROPIC_API_KEY")
say "Will set: ${names[*]}  (values hidden)"
if confirm "Set these secrets on project ${NEW_PROJECT_REF}?"; then
  SECRETS_TMP="$(umask 077; mktemp "${TMPDIR:-/tmp}/nn-secrets.XXXXXX")"
  chmod 600 "$SECRETS_TMP"
  {
    printf 'GROQ_API_KEY=%s\n' "$GROQ_KEY"
    [[ -n "$SARVAM_KEY" ]]    && printf 'SARVAM_API_KEY=%s\n' "$SARVAM_KEY"
    [[ -n "$ANTHROPIC_KEY" ]] && printf 'ANTHROPIC_API_KEY=%s\n' "$ANTHROPIC_KEY"
    true
  } > "$SECRETS_TMP"
  set +e
  run npx --yes supabase secrets set --env-file "$SECRETS_TMP" --project-ref "$NEW_PROJECT_REF"
  rc=$?
  set -e
  rm -f "$SECRETS_TMP"; SECRETS_TMP=""
  if (( rc != 0 )); then warn "Setting secrets failed (exit $rc). Re-run the wizard."; exit 1; fi
  printf '  %s✓%s secrets set; temp file deleted\n' "$GREEN" "$RESET"
  note "Check names (values are never shown, only a hash):"
  run npx --yes supabase secrets list --project-ref "$NEW_PROJECT_REF" || true
else
  SKIPPED+=("set secrets: npx supabase secrets set GROQ_API_KEY ... --project-ref ${NEW_PROJECT_REF}")
fi
# The wizard no longer needs the keys in memory.
GROQ_KEY=""; SARVAM_KEY=""; ANTHROPIC_KEY=""
pause "Press Enter to continue"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Deploy the three edge functions"
say "Deploying uploads the function code to your project so it can run there."
note "--use-api = Supabase bundles the code on its servers, so Docker isn't needed."
note "--no-verify-jwt matches config.toml (verify_jwt = false): the functions accept"
note "calls carrying just the publishable key, without a signed-in user."
note "JWT = a signed token proving who a user is. This app has no user accounts."
if confirm "Deploy ${FUNCTIONS[*]} to ${NEW_PROJECT_REF}?"; then
  for fn in "${FUNCTIONS[@]}"; do
    if ! run npx --yes supabase functions deploy "$fn" \
         --project-ref "$NEW_PROJECT_REF" --no-verify-jwt --use-api; then
      warn "Deploy of $fn with --use-api failed."
      note "If the error says the flag is unknown, your CLI is old: re-run with"
      note "'npx --yes supabase@latest ...'. Without --use-api the CLI bundles locally,"
      note "which may need Docker Desktop running (open -a Docker)."
      if confirm "Retry $fn without --use-api?"; then
        run npx --yes supabase functions deploy "$fn" \
          --project-ref "$NEW_PROJECT_REF" --no-verify-jwt \
          || { warn "Deploy failed again. See the error above."; exit 1; }
      else
        SKIPPED+=("deploy $fn"); continue
      fi
    fi
    printf '  %s✓%s deployed %s\n' "$GREEN" "$RESET" "$fn"
  done
  open_url "https://supabase.com/dashboard/project/${NEW_PROJECT_REF}/functions"
  step "You should see all three functions listed in the dashboard."
else
  SKIPPED+=("deploy functions: npx supabase functions deploy <name> --project-ref ${NEW_PROJECT_REF} --no-verify-jwt --use-api")
fi
pause "Press Enter to continue"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Back up the teammate's .env and point the app at your project"
say "The frontend reads .env to know which Supabase project to call."
note "Vite only exposes variables starting with VITE_ to browser code."
if git ls-files --error-unmatch .env >/dev/null 2>&1; then
  warn ".env is TRACKED by git (committed), even though .gitignore lists it."
  note ".gitignore only affects untracked files, so editing .env WILL show as a change"
  note "and could be committed by accident, replacing the team's values with yours."
fi
# Never overwrite an existing backup: on a re-run, .env already holds YOUR values.
if [[ -f "$BACKUP_FILE" ]]; then
  note "Backup already exists at .env.teammate.bak, keeping it untouched."
elif [[ -f "$ENV_FILE" ]]; then
  cp "$ENV_FILE" "$BACKUP_FILE"
  printf '  %s✓ backed up%s .env → .env.teammate.bak\n' "$GREEN" "$RESET"
fi
exclude_locally ".env.teammate.bak"
printf '\n'
note "Option: 'git update-index --skip-worktree .env' tells git on THIS machine to"
note "pretend .env is unchanged, so 'git add -A' / 'git commit -a' won't pick it up."
note "Undo it any time with: git update-index --no-skip-worktree .env"
note "Catch: if a teammate changes .env upstream, git pull will complain; undo first."
if git ls-files --error-unmatch .env >/dev/null 2>&1 && confirm "Mark .env skip-worktree now? (recommended)"; then
  run git update-index --skip-worktree .env
  printf '  %s✓%s git will ignore your local .env edits\n' "$GREEN" "$RESET"
else
  warn "Remember: do NOT commit .env. Check 'git status' before every commit."
fi
printf '\n'
say "New values (all public, safe to show):"
note "VITE_SUPABASE_URL=${NEW_SUPABASE_URL}"
note "VITE_SUPABASE_PROJECT_ID=${NEW_PROJECT_REF}"
note "VITE_SUPABASE_PUBLISHABLE_KEY=${NEW_PUBLISHABLE_KEY:0:20}..."
if confirm "Write these to .env?"; then
  write_env VITE_SUPABASE_URL "\"${NEW_SUPABASE_URL}\""
  write_env VITE_SUPABASE_PUBLISHABLE_KEY "\"${NEW_PUBLISHABLE_KEY}\""
  write_env VITE_SUPABASE_PROJECT_ID "\"${NEW_PROJECT_REF}\""
else
  SKIPPED+=("write VITE_SUPABASE_* to .env")
fi
pause "Press Enter to continue"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Smoke test: call analyze-image directly"
say "This proves the deployed function + your Groq secret work before opening the app."
note "We send a tiny built-in 32x32 test image (red top, blue bottom) with curl."
note "Expect HTTP 200 and JSON with a 'description'. The model may say something vague"
note "about colours: that's fine; it means the whole chain works."
TEST_PNG_B64="iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAALUlEQVR42u3NsQkAAAzDsBzW/+lZvaJDQODZys68FgAAAABUAM//BQAAAEAFcNLfAExt+YfPAAAAAElFTkSuQmCC"
if confirm "Send the test request now?"; then
  resp_file="$(mktemp "${TMPDIR:-/tmp}/nn-smoke.XXXXXX")"
  http_code="$(curl -sS -o "$resp_file" -w '%{http_code}' --max-time 30 \
    -X POST "${NEW_SUPABASE_URL}/functions/v1/analyze-image" \
    -H "Content-Type: application/json" \
    -H "apikey: ${NEW_PUBLISHABLE_KEY}" \
    -H "Authorization: Bearer ${NEW_PUBLISHABLE_KEY}" \
    -d "{\"imageBase64\":\"data:image/png;base64,${TEST_PNG_B64}\",\"mode\":\"general\"}" \
    || true)"
  [[ "$http_code" =~ ^[0-9]{3}$ ]] || http_code="000"
  say "HTTP ${http_code}"
  note "$(head -c 600 "$resp_file")"
  rm -f "$resp_file"
  case "$http_code" in
    200) printf '  %s✓ analyze-image works on your project%s\n' "$GREEN" "$RESET" ;;
    404) warn "Function not found: the deploy in stage 8 didn't happen or failed." ;;
    401) warn "Unauthorized: wrong publishable key, or deployed without --no-verify-jwt." ;;
    500) warn "'API key not configured' means the secrets in stage 7 weren't set." ;;
    503) warn "All vision models failed: check the Groq key, or Groq may be busy. Retry later." ;;
    000) warn "No response: check your internet connection and the project URL." ;;
    *)   warn "Unexpected result. Check logs: dashboard → Edge Functions → analyze-image → Logs." ;;
  esac
else
  SKIPPED+=("smoke test (see docs/SETUP_OWN_BACKEND.md for the curl command)")
fi
pause "Press Enter to continue"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Run the app, and how to roll back"
say "Start the dev server and try the vision page in Chrome."
step "In a new terminal:  cd \"$REPO_ROOT\" && npm run dev"
step "Open http://localhost:8080/vision and allow the camera."
step "If it was already running, restart it: Vite reads .env only at startup."
note "Browser DevTools → Network: requests should now go to ${NEW_SUPABASE_URL}."
printf '\n'
say "${BOLD}Rollback${RESET} (go back to the teammate's backend):"
step "cp .env.teammate.bak .env           # restore the teammate's values"
step "git update-index --no-skip-worktree .env   # only if you enabled skip-worktree"
step "git checkout -- .env                # alternative: restore the committed version"
note "Your Supabase project, secrets and functions stay; delete the project from the"
note "dashboard (Settings → General → Delete project) only if you no longer want it."
pause "Press Enter to finish"

finish
